% timeseries generated by an ornstein-uhlenbeck process
% code snippet from https://math.stackexchange.com/questions/1287634/implementing-ornstein-uhlenbeck-in-matlab

th = 1;
mu = 1.2;
sig = 0.1;
dt = 1e-1;
T=20;	% time length
N=5;	% number of variables

t = 0:dt:20;             % Time vector
nt=length(t);

x0 = 1.2;                 % Set initial condition
rng(1);                 % Set random seed
ex = exp(-th*t);

x=zeros(N,nt);

for i=1:N
	x(i,:) = x0*ex+mu*(1-ex)+sig*ex.*cumsum(exp(th*t).*[0 sqrt(dt)*randn(1,length(t)-1)]);
end

figure;
plot(t,x);

cm=cov(x');
vr=(sum(sum(cm))-sum(diag(cm)))/sum(diag(cm))
